/**
 * Sprint 1.1 (2026-04-16) — AI-Output-Label
 *
 * Visible "🤖 KI-generiert" indicator placed on every AI-generated output:
 * chat assistant bubbles, AI email drafts, AI summaries, etc.
 *
 * Mandated by EU AI Act Art. 50 (in force from 2026-08-02): users must be
 * able to recognise that content has been generated by an AI system.
 *
 * Design philosophy:
 *   - Always visible by default (no hover-only labels — Art. 50 wants it
 *     "clearly perceptible to the natural person concerned").
 *   - Three sizes (sm/md/lg) so the badge fits inline-with-text, in
 *     headers, and as a stand-alone disclaimer.
 *   - Optional `model` and `tooltip` props let callers expose "Claude Opus 4.6"
 *     and a verbose disclosure without cluttering the default rendering.
 */

import * as React from 'react';

export type AiOutputBadgeSize = 'sm' | 'md' | 'lg';
export type AiOutputBadgeVariant = 'inline' | 'subtle' | 'prominent';

export interface AiOutputBadgeProps {
  /** Compact form for sidebars/icons; "md" is the default chat-bubble size. */
  size?: AiOutputBadgeSize;
  /** Visual weight: subtle (chat bubbles), inline (within text), prominent (banners). */
  variant?: AiOutputBadgeVariant;
  /** Optional model id rendered after the label, e.g. "Claude Opus 4.6". */
  model?: string;
  /** Override the default German label. */
  label?: string;
  /** Hover/tap tooltip with a longer disclosure. */
  tooltip?: string;
  /** Additional className for layout-only adjustments. */
  className?: string;
}

const SIZE_CLASSES: Record<AiOutputBadgeSize, string> = {
  sm: 'text-[10px] px-1.5 py-0.5 gap-1',
  md: 'text-[11px] px-2 py-0.5 gap-1.5',
  lg: 'text-xs px-2.5 py-1 gap-2',
};

const VARIANT_CLASSES: Record<AiOutputBadgeVariant, string> = {
  subtle: 'bg-glass-bg border border-glass-border text-text-muted',
  inline: 'bg-violet-500/10 border border-violet-500/30 text-violet-500',
  prominent: 'bg-amber-500/15 border border-amber-500/40 text-amber-600 font-medium',
};

/**
 * Default label is German per ZenAI primary market.
 * Callers in i18n-aware contexts pass `label` explicitly.
 */
const DEFAULT_LABEL = 'KI-generiert';

/**
 * Default tooltip text quoted to make the EU AI Act disclosure explicit.
 */
const DEFAULT_TOOLTIP =
  'Dieser Inhalt wurde mit KI erzeugt. Bitte vor wichtiger Verwendung prüfen. (EU AI Act Art. 50)';

export const AiOutputBadge: React.FC<AiOutputBadgeProps> = ({
  size = 'md',
  variant = 'subtle',
  model,
  label = DEFAULT_LABEL,
  tooltip,
  className,
}) => {
  return (
    <span
      role="note"
      aria-label={tooltip ?? DEFAULT_TOOLTIP}
      title={tooltip ?? DEFAULT_TOOLTIP}
      data-ai-output-badge
      className={[
        'inline-flex items-center rounded-full font-mono uppercase tracking-wide',
        SIZE_CLASSES[size],
        VARIANT_CLASSES[variant],
        className ?? '',
      ].join(' ').trim()}
    >
      <span aria-hidden="true">🤖</span>
      <span>{label}</span>
      {model ? <span className="opacity-70">· {model}</span> : null}
    </span>
  );
};

export default AiOutputBadge;
