-- Phase 98: Migration Tracking System
-- Creates public.schema_migrations to track all applied migrations
-- Registers all existing migration files as already applied

CREATE TABLE IF NOT EXISTS public.schema_migrations (
  filename VARCHAR(255) PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  checksum TEXT
);

-- Register all existing migrations (93 files as of Phase 97)
INSERT INTO public.schema_migrations (filename) VALUES
  ('add_learning_creative_schemas.sql'),
  ('add_missing_ideas_columns.sql'),
  ('add_preferred_contexts.sql'),
  ('add_session_type.sql'),
  ('create_ai_activity_log.sql'),
  ('create_episodic_memories_table.sql'),
  ('fix_ai_activity_log_columns.sql'),
  ('fix_business_snapshot_unique.sql'),
  ('fix_context_check_constraints.sql'),
  ('fix_digests_schema.sql'),
  ('fix_domain_focus_table.sql'),
  ('fix_episodic_memories_schema.sql'),
  ('fix_idea_move_schema.sql'),
  ('fix_idea_relations_columns.sql'),
  ('fix_ideas_is_favorite.sql'),
  ('fix_missing_schema_elements.sql'),
  ('fix_notification_history_and_activity_log.sql'),
  ('fix_proactive_research_focus_fk.sql'),
  ('fix_public_schema_tables.sql'),
  ('fix_rls_and_schema_parity.sql'),
  ('fix_schema_parity_and_constraints.sql'),
  ('fix_sql_functions.sql'),
  ('fix_user_profile_schema.sql'),
  ('missing_tables_27.sql'),
  ('phase04_integrations_webhooks.sql'),
  ('phase32_document_vault.sql'),
  ('phase34_business_manager.sql'),
  ('phase35_36_combined.sql'),
  ('phase35_calendar.sql'),
  ('phase36_focus_research_loop.sql'),
  ('phase37_memory_governance.sql'),
  ('phase37_planner.sql'),
  ('phase37_proactive_digests.sql'),
  ('phase37_procedural_memory.sql'),
  ('phase37_reflection_insights.sql'),
  ('phase38_agent_executions.sql'),
  ('phase38_email.sql'),
  ('phase38_task_favorites.sql'),
  ('phase39_imap_sync.sql'),
  ('phase40_calendar_sync.sql'),
  ('phase41_google_maps.sql'),
  ('phase42_autonomous_agents.sql'),
  ('phase44_mcp_ecosystem.sql'),
  ('phase45_fix_agent_tokens_jsonb.sql'),
  ('phase46_thinking_chains.sql'),
  ('phase49_advanced_rag.sql'),
  ('phase50_analytics.sql'),
  ('phase51_plugins.sql'),
  ('phase53_memory_insights.sql'),
  ('phase55_mcp_connections.sql'),
  ('phase56_auth.sql'),
  ('phase57_voice.sql'),
  ('phase58_graphrag.sql'),
  ('phase59_memory.sql'),
  ('phase60_a2a.sql'),
  ('phase61_observability.sql'),
  ('phase62_security.sql'),
  ('phase63_sleep_compute.sql'),
  ('phase64_agent_identity.sql'),
  ('phase65_multiuser_core.sql'),
  ('phase65_rls_policies.sql'),
  ('phase65_supplement_missing_tables.sql'),
  ('phase67_performance_indexes.sql'),
  ('phase69_smart_suggestions.sql'),
  ('phase72_emotional_memory.sql'),
  ('phase73_ai_traces.sql'),
  ('phase75_extensions.sql'),
  ('phase76_agent_executions_userid.sql'),
  ('phase76_fix_public_chat_user_id.sql'),
  ('phase76_multiuser_gap_fix.sql'),
  ('phase76_password_reset.sql'),
  ('phase76_production_audit_fixes.sql'),
  ('phase87_memory.sql'),
  ('phase88_proactive.sql'),
  ('phase89_agent_evolution.sql'),
  ('phase90_voice.sql'),
  ('phase91_assistant.sql'),
  ('phase92_digital_twin.sql'),
  ('phase93_automation.sql'),
  ('phase95_search.sql'),
  ('phase96_narrative.sql'),
  ('phase97_quality_indexes.sql'),
  ('phase_browser.sql'),
  ('phase_contacts.sql'),
  ('phase_context_engineering.sql'),
  ('phase_durable_agents.sql'),
  ('phase_finance.sql'),
  ('phase_governance.sql'),
  ('phase_meeting_audio.sql'),
  ('phase_proactive.sql'),
  ('phase_proactive_engine.sql'),
  ('phase_screen_memory.sql'),
  ('phase_temporal_kg.sql'),
  ('sync_all_schemas_full_parity.sql'),
  -- Phase 98 migrations (this sprint)
  ('phase98_migration_tracking.sql'),
  ('phase98_missing_fks.sql'),
  ('phase98_text_limits.sql')
ON CONFLICT (filename) DO NOTHING;
