#!/usr/bin/env bash
# build_arxiv_v3.sh — Build arXiv V3 replacement package from
# docs/papers/latex/arxiv-bundle/.
#
# IMPORTANT: arxiv-bundle/zenbrain.tex is a synced VIEW of the master
# docs/papers/latex/zenbrain-submission.tex (with preprint-mode toggle +
# real author block). After ANY edit to zenbrain-submission.tex, sync via:
#   cp docs/papers/latex/zenbrain-submission.tex docs/papers/latex/arxiv-bundle/zenbrain.tex
# then in the COPY (arxiv-bundle/zenbrain.tex):
#   1. toggle preprint mode: \usepackage{neurips_2025} → \usepackage[preprint]{neurips_2025}
#      (this script auto-applies the toggle on the build copy if you forget,
#      but doing it in-source keeps git diffs clean).
#   2. comment out \author{Anonymous} and uncomment the real
#      \author{ Alexander Bering \\ Zensation AI \\ \texttt{research@zensation.ai} }
#      block. arXiv REJECTS anonymous submissions — the build script enforces
#      this with a guard that fails loudly if Anonymous is still active.
# The bib must also be synced: cp docs/papers/latex/zenbrain.bib docs/papers/latex/arxiv-bundle/zenbrain.bib
#
# Use this AFTER arXiv V2 is approved (or in parallel with NeurIPS submission)
# to push a V3 with the latest defensive analyses (§"Additional Defensive
# Analyses": Bayesian Calibration, Power Analysis, Failure Modes) plus the
# mem0 v2.0.0 disclosure and any other post-V2 polish.
#
# What it does:
#   1. Copy arxiv-bundle/ → build/arxiv-v3/
#   2. Ensure preprint mode active (with author info)
#   3. Compile via tectonic
#   4. Verify page-cap (§7 ≤ page 9)
#   5. Verify all bibliography refs resolve (no [?])
#   6. Generate ZIP for arXiv replacement upload
#   7. Print SHA-256 of the ZIP for posterity
#
# Usage:
#   bash docs/papers/scripts/build_arxiv_v3.sh
#   # → build/arxiv-v3/zenbrain-v3.zip  (upload to arXiv)
#
# Requires: tectonic, pdfinfo, pdftotext, zip, shasum

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SOURCE="$REPO/docs/papers/latex/arxiv-bundle"
BUILD="$REPO/build/arxiv-v3"
TEX="$BUILD/zenbrain.tex"
PDF="$BUILD/zenbrain.pdf"
DATE_STAMP=$(date +%Y-%m-%d)
ZIP="$BUILD/arxiv-zenbrain-${DATE_STAMP}-v3.zip"

red()    { printf '\033[0;31m%s\033[0m\n' "$*"; }
green()  { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$*"; }
bold()   { printf '\033[1m%s\033[0m\n' "$*"; }

bold "=== arXiv V3-Replace Builder ==="
echo "Source:  $SOURCE"
echo "Build:   $BUILD"
echo

# Tool check
for tool in tectonic pdfinfo pdftotext zip shasum; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    red "ERROR: $tool not installed"
    exit 1
  fi
done

# 1. Clean + copy
rm -rf "$BUILD"
mkdir -p "$BUILD"
cp -R "$SOURCE/." "$BUILD/"
green "✓ Source copied"

# 2. Ensure preprint mode
sed -i.bak \
  -e 's/^\\usepackage{neurips_2025}$/% \\usepackage{neurips_2025}/' \
  -e 's/^% \\usepackage\[preprint\]{neurips_2025}$/\\usepackage[preprint]{neurips_2025}/' \
  "$TEX"
rm -f "$TEX.bak"

ACTIVE_PKG=$(grep "^[^%]*neurips_2025" "$TEX" | head -1)
if ! echo "$ACTIVE_PKG" | grep -q "preprint"; then
  red "ERROR: preprint mode toggle failed"
  echo "  Active line: $ACTIVE_PKG"
  exit 1
fi
green "✓ Preprint mode active: $ACTIVE_PKG"

# 2b. Author-deanonymization guard.
# arXiv rejects anonymous submissions (MOD-89216, 2026-05-01). The arxiv-bundle
# source must carry the real \author{} block. If a re-sync from master left
# \author{Anonymous} active, fail loudly so we never re-upload an anonymous PDF.
if grep -E '^\s*\\author\{Anonymous\}\s*$' "$TEX" >/dev/null; then
  red "ERROR: \\author{Anonymous} still active in arxiv-bundle copy."
  red "  arXiv rejects anonymous submissions. Re-apply deanonymization:"
  red "    open docs/papers/latex/arxiv-bundle/zenbrain.tex"
  red "    comment out  \\author{Anonymous}"
  red "    uncomment    \\author{ Alexander Bering / Zensation AI / research@zensation.ai }"
  exit 1
fi
if ! grep -E '^\s*\\author\{\s*$' "$TEX" >/dev/null \
   || ! grep -F 'Alexander Bering' "$TEX" >/dev/null \
   || ! grep -F 'research@zensation.ai' "$TEX" >/dev/null; then
  red "ERROR: real author block not found in arxiv-bundle copy."
  red "  Expected an active \\author{ ... Alexander Bering ... research@zensation.ai ... }"
  exit 1
fi
green "✓ Author block deanonymized (Alexander Bering / Zensation AI)"

# 3. Compile
echo
echo "Compiling…"
cd "$BUILD"
if ! tectonic -X compile zenbrain.tex --keep-intermediates 2>&1 | tail -5; then
  red "ERROR: tectonic compile failed"
  exit 1
fi
green "✓ Compiled"

# 3b. Verify .bbl exists and contains expected keys (catches stale-bbl scenarios)
if [ ! -f zenbrain.bbl ]; then
  red "ERROR: zenbrain.bbl not generated by tectonic"
  exit 1
fi
BBL_LINES=$(wc -l < zenbrain.bbl | tr -d ' ')
if [ "$BBL_LINES" -lt 100 ]; then
  red "ERROR: zenbrain.bbl is suspiciously short ($BBL_LINES lines) — bib resolution may have failed"
  exit 1
fi
green "✓ Fresh zenbrain.bbl: $BBL_LINES lines"

# 4. Page-cap
PAGES=$(pdfinfo "$PDF" | awk '/Pages:/{print $2}')
DISCUSSION_PAGE=""
for p in 7 8 9 10 11 12; do
  if pdftotext -f "$p" -l "$p" "$PDF" - 2>/dev/null | grep -q "^7 Discussion"; then
    DISCUSSION_PAGE="$p"
    break
  fi
done
echo "PDF: $PAGES pages, §7 Discussion on page ${DISCUSSION_PAGE:-???}"
if [ -z "$DISCUSSION_PAGE" ] || [ "$DISCUSSION_PAGE" -gt 9 ]; then
  red "✗ Page-cap broken; aborting V3 build"
  exit 1
fi
green "✓ Page-cap OK"

# 5. Unresolved-ref check (multiple patterns to catch all natbib/biblatex variants)
UNRESOLVED_BRACKET=$(pdftotext "$PDF" - 2>/dev/null | grep -c '\[?\]' || true)
UNRESOLVED_QQ=$(pdftotext "$PDF" - 2>/dev/null | grep -c '??' || true)
TOTAL_UNRESOLVED=$((UNRESOLVED_BRACKET + UNRESOLVED_QQ))
if [ "$TOTAL_UNRESOLVED" -gt 0 ]; then
  red "✗ Unresolved refs in PDF: [?]=$UNRESOLVED_BRACKET, ??=$UNRESOLVED_QQ"
  pdftotext "$PDF" - 2>/dev/null | grep -B1 -A1 '\[?\]\|??' | head -20
  exit 1
fi
green "✓ All references resolved"

# 6. Build ZIP (arXiv-required structure)
echo
echo "Building ZIP…"
cd "$BUILD"
# arXiv expects: tex, sty, bbl (built artifact), figures/, tables/
zip -q -r "$ZIP" \
  zenbrain.tex \
  zenbrain.bib \
  neurips_2025.sty \
  zenbrain.bbl \
  figures/ \
  tables/ \
  -x "*.aux" -x "*.log" -x "*.out" -x "*.bak"

# Include the compiled PDF for arXiv preview, but in a way arXiv is OK with:
# arXiv only wants .tex source + the compiled pdf is generated server-side.
# We include zenbrain.bbl so the bibliography compiles without bibtex.

ZIP_SIZE=$(wc -c < "$ZIP" | tr -d ' ')
ZIP_SHA=$(shasum -a 256 "$ZIP" | awk '{print $1}')

green "✓ ZIP built"
echo
echo "  File:   $ZIP"
echo "  Size:   $ZIP_SIZE bytes"
echo "  SHA-256:$ZIP_SHA"
echo
bold "=== READY for arXiv V3-Replacement ==="
echo "Workflow:"
echo "  1. Login to arxiv.org"
echo "  2. Go to your submission ($(grep -r 'submit/[0-9]' "$REPO" 2>/dev/null | head -1 | grep -oE 'submit/[0-9]+' | head -1 || echo 'check user dashboard'))"
echo "  3. Click 'Replace' (only available after V2 is announced)"
echo "  4. Upload: $ZIP"
echo "  5. Verify Compiler=pdflatex, Top-Level=zenbrain.tex, KEEP zenbrain.bbl"
echo "  6. Click Accept and Continue → Process → Metadata → Preview → Submit"
echo "  7. Re-moderation expected: 0–1 day"
